### PR TITLE
Add bash completion scripts

### PR DESCRIPTION
**Pull request by ejegg**
I haven't quite got the package building locally, but according to https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#customrules it seems like this should do it.

### CODE REVIEW

**Comment by adamwight** [comment]
Cool idea!  I'm trying to build the .deb in a VM, will get back once I can
smoke test it.

**Comment by ejegg** [comment]
Got it building! That last commit adds the missing 'with' option to the dh command, and points to a completion script in the main source repo instead of here. Makes sense to keep the completion script in the same place as the run-job wrapper.

This commit updates the completion in the main repo: https://gerrit.wikimedia.org/r/388158

**Comment by adamwight** [comment]
I've built and installed, but it's not working for me.  Does the actual completion work for you?

I tried sourcing /etc/bash_completion and /usr/share/bash-completion/bash_completion, and tried "exec bash".  I've copied job.example.yaml to /var/lib/process-control.  In all cases, "run-job -j <tab>" and "run-job -j j<tab>" result in nothing happening.

One suspicious detail is that /usr/share/bash-completion/completions/process-control is the only file in that directory that uses "tools/autocomplete.sh", out of 700+ other packages.  The entire contents of that file are,
> tools/autocomplete.sh   run-job

Oh.  It's something simple, your last commit removes the actual script and says something about the "main repo".  Uncommitted changes, maybe?

**Comment by adamwight** [comment]
Rebuilt it with your new upstream, it works great!  Thank you!

**Pull request merged**
